name: descubra_rr
description: Descubra RR - Explore. Descubra. Desbloqueie.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  shared_preferences: ^2.3.2
  latlong2: ^0.9.1
  flutter_map: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
